language: python

python:
  - "2.7"

addons:
  postgresql: "9.3"
# debsources uses 9.4

notifications:
  email: false

before_install:
  - pwd
  - mkdir cloc
  - sudo apt-get update -qq
  - sudo apt-get install -y tango-icon-theme debmirror exuberant-ctags sloccount dpkg-dev libapt-pkg-dev diffstat
  - wget https://raw.githubusercontent.com/AlDanial/cloc/master/cloc -P cloc
  - chmod +x cloc/cloc
  - export PATH=$PATH:$PWD/cloc
  - git clone https://github.com/file/file.git ../file && pip install -e ../file/python
  - pip install https://launchpad.net/python-apt/main/0.7.8/+download/python-apt-0.8.5.tar.gz
  - pip install flake8

# apt's python-magic and pypi's python-magic are different.
# We need the one in apt, and since it's not in pypi, it's installed
# through wget (because Travis uses virtual env without dist-packages).
# Will likely break soon.

# packages missing: libjs-highlight (not in Ubuntu 12.04)

before_script:
  - cp etc/config.travis.ini etc/config.ini
  - sed -i 's?TRAVISWD?'`pwd`'?' etc/config.ini
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/debsources
  - psql -c 'create database debsources;' -U postgres
  - bin/debsources-dbadmin --createdb postgresql://postgres@localhost/debsources
  - bin/debsources-update -vv

script: make check test-travis

branches:
  except:
    - bugs
