CREATE TYPE cloc_languages as ENUM(
    "ABAP",
    "ActionScript",
    "Ada",
    "ADSO/IDSM",
    "AMPLE",
    "Ant",
    "Apex Trigger",
    "Arduino Sketch",
    "ASP",
    "ASP.Net",
    "AspectJ",
    "Assembly",
    "AutoHotkey",
    "awk",
    "Bourne Again Shell",
    "Bourne Shell",
    "C",
    "C Shell",
    "C#",
    "C++",
    "C/C++ Header",
    "CCS",
    "Clojure",
    "ClojureC",
    "ClojureScript",
    "CMake",
    "COBOL",
    "CoffeeScript",
    "ColdFusion",
    "ColdFusion CFScript",
    "Coq",
    "Crystal",
    "CSON",
    "CSS",
    "CUDA",
    "Cython",
    "D",
    "DAL",
    "Dart",
    "diff",
    "DITA",
    "DOORS Extension Language",
    "DOS Batch",
    "DTD",
    "dtrace",
    "ECPP",
    "EEx",
    "Elixir",
    "Elm",
    "ERB",
    "Erlang",
    "Expect",
    "F#",
    "Focus",
    "Forth",
    "Fortran 77",
    "Fortran 90",
    "Fortran 95",
    "GDScript",
    "Go",
    "Grails",
    "Groovy",
    "Haml",
    "Handlebars",
    "Harbour",
    "Haskell",
    "HLSL",
    "HTML",
    "IDL",
    "InstallShield",
    "Java",
    "JavaScript",
    "JavaServer Faces",
    "JCL",
    "JSON",
    "JSP",
    "Julia",
    "Kermit",
    "Korn Shell",
    "Kotlin",
    "LESS",
    "lex",
    "Lisp",
    "LiveLink OScript",
    "Lua",
    "m4",
    "make",
    "MATLAB",
    "Maven",
    "Modula3",
    "MSBuild script",
    "MUMPS",
    "Mustache",
    "MXML",
    "NAnt script",
    "NASTRAN DMAP",
    "Nemerle",
    "Objective C",
    "Objective C++",
    "OCaml",
    "OpenCL",
    "Oracle Forms",
    "Oracle Reports",
    "Pascal",
    "Pascal/Puppet",
    "Patran Command Language",
    "Perl",
    "PHP",
    "PHP/Pascal",
    "Pig Latin",
    "PL/I",
    "PowerBuilder",
    "PowerShell",
    "Prolog",
    "Protocol Buffers",
    "PureScript",
    "Python",
    "QML",
    "Qt",
    "Qt Project",
    "R",
    "Racket",
    "Razor",
    "Rexx",
    "RobotFramework",
    "Ruby",
    "Ruby HTML",
    "Rust",
    "SAS",
    "SASS",
    "Scala",
    "sed",
    "SKILL",
    "SKILL++",
    "Smarty",
    "Softbridge Basic",
    "SQL",
    "SQL Data",
    "SQL Stored Procedure",
    "Standard ML",
    "Stylus",
    "Swift",
    "Tcl/Tk",
    "Teamcenter met",
    "Teamcenter mth",
    "Titanium Style Sheet",
    "Twig",
    "TypeScript",
    "Unity-Prefab",
    "Vala",
    "Vala Header",
    "Velocity Template Language (vm)",
    "Verilog-SystemVerilog",
    "VHDL",
    "vim script",
    "Visual Basic",
    "Visual Fox Pro",
    "Visualforce Component",
    "Visualforce Page",
    "Windows Message File",
    "Windows Module Definition",
    "Windows Resource File",
    "WiX include",
    "WiX source",
    "WiX string localization",
    "XAML",
    "xBase",
    "xBase Header",
    "XHTML",
    "XMI",
    "XML",
    "XQuery",
    "XSD",
    "XSLT",
    "yacc",
    "YAML",
    "zsh",
);

CREATE TABLE cloccounts (
    id SERIAL NOT NULL,
    file_id BIGINT NOT NULL,
    package_id BIGINT NOT NULL,
    code_count Integer NOT NULL,
    comment_count Integer,
    blank_count Integer,
    language cloc_languages NOT NULL,
    CONSTRAINT file_metas_file_id_fkey
    FOREIGN KEY (file_id) REFERENCES files(id)
    ON DELETE CASCADE,
    CONSTRAINT file_metas_package_id_fkey
    FOREIGN KEY (package_id) REFERENCES packages(id)
    ON DELETE CASCADE,
PRIMARY KEY (id)
);

CREATE INDEX ix_cloccounts_file_id ON cloccounts (file_id);
